### ISSUE TITLE
unable to run on web

### ISSUE THREAD

**Issue by jabar-7** [TheWidlarzGroup/react-native-video-player#147]
ERROR in ./node_modules/react-native/Libraries/Image/AssetSourceResolver.js 1:407-439
Module not found: Error: Can't resolve '../Utilities/Platform' in 'D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Image'  
resolve '../Utilities/Platform' in 'D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Image'
  using description file: D:\projects\rn\WebAndMobile-RN\node_modules\react-native\package.json (relative path: ./Libraries/Image)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: D:\projects\rn\WebAndMobile-RN\node_modules\react-native\package.json (relative path: ./Libraries/Utilities/Platform)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform doesn't exist
      .web.tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform.web.tsx doesn't exist
      .web.ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform.web.ts doesn't exist
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform.web.js doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform.js doesn't exist
      as directory
        D:\projects\rn\WebAndMobile-RN\node_modules\react-native\Libraries\Utilities\Platform doesn't exist
 @ ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 1:96-128
 @ ./node_modules/react-native-video/Video.js 1:1484-1542
 @ ./node_modules/react-native-video-player/index.js 1:1958-1987
 @ ./src/VideoView.js 1:322-358
 @ ./AppNavigator.js 1:707-733
 @ ./App.web.js 1:348-373
 @ ./index.web.js 1:202-218

**Comment by moskalakamil** [comment]
should be fixed, since react-native-video works on web. Check with react-native-video > 6.8.0
