### ISSUE TITLE
TypeError: _MaterialIcons.default.propTypes is undefined

### ISSUE THREAD

**Issue by ploveland** [TheWidlarzGroup/react-native-video-player#154]
After going through the steps, including copying over the Material font to the Info.plist file, as well as the line for the gradle file, I am getting the TypeError above. I'm using React 17.0.1 and React Native 63.4.

**Comment by azeezWebsultanate** [comment]
Error message : TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants

<img width="442" alt="Screenshot 2022-05-31 at 7 11 30 PM" src="https://user-images.githubusercontent.com/87024456/171190016-2ab8038b-3356-4911-b458-7bd368db2c98.png">

I am facing the same issue in ios while I have to do pod install and icon install its keeps giving me the same issue

<img width="1440" alt="Screenshot 2022-05-31 at 7 23 53 PM" src="https://user-images.githubusercontent.com/87024456/171190546-7f94064e-1ee3-431b-a357-acc4c484e8a7.png">

And when I do pod install it doesn't add it in the pod file too.
