### ISSUE TITLE
Maintenance update: looking for maintainers

### ISSUE THREAD

**Issue by TheDanielMoli** [TheWidlarzGroup/react-native-video-player#157]
I no longer work for the company using this library. When I started using it, the owner of the repo @cornedor was looking for maintainers and I joined.

I will no longer work on this because I don't need it anymore. If you are willing to maintain the repo, please ask @cornedor to give you access.

**Comment by AshwinTayson** [comment]
@cornedor Are you till looking for maintainers?

**Comment by cornedor** [comment]
Yes :-)

**Comment by smasinde** [comment]
Do you still need maintainers?

**Comment by Erichy-dev** [comment]
are you still seeking maintainers?

**Comment by Okelm** [comment]
We have moved the library to @TheWidlarzGroup and now tring to build the roadmap in here, please chip in! https://github.com/TheWidlarzGroup/react-native-video-player/discussions/186
