### ISSUE TITLE
React native video issue in android

### ISSUE THREAD

**Issue by avigmaproject** [TheWidlarzGroup/react-native-video-player#160]
A problem occurred evaluating project ':react-native-video'.
> Could not find method provided() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
<img width="441" alt="Screen Shot 2022-07-21 at 5 20 26 PM" src="https://user-images.githubusercontent.com/71446696/180207029-adefd774-fd8d-47e3-a851-1544c68790d4.png">
<img width="934" alt="Screen Shot 2022-07-21 at 5 20 17 PM" src="https://user-images.githubusercontent.com/71446696/180207055-c2cc7ef3-e19d-4795-b1e4-b8b4580d8077.png">

.

**Comment by sangeethps2255** [comment]
I got the same issue

**Comment by Muhammad-Sufian** [comment]
go to node_modules > react-native-video and inside dependencies change:
provided to compileOnly
compile to implementation

**Comment by avigmaproject** [comment]
go to node_modules > react-native-video and inside dependencies change:

provided to implementation
