### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by pushpender-singh-ap** [TheWidlarzGroup/react-native-video-player#176]
<img width="612" alt="Screenshot 2023-05-22 at 4 32 58 PM" src="https://github.com/cornedor/react-native-video-player/assets/73298854/53a98826-6676-4a22-b668-1ef0b5287850">

**Comment by naveedAhmed007** [comment]
npm install react-native  --legacy-peer-deps

**Comment by moskalakamil** [comment]
fixed! now library is upgraded to the latest v6 react-native-video
