### ISSUE TITLE
iOS video paly not working

### ISSUE THREAD

**Issue by PrudhviBanki** [TheWidlarzGroup/react-native-video-player#180]
<VideoPlayer
                                video={{ uri: videoLink }}
                                onLoad={onVideoLoad}
                                videoWidth={1600}
                                videoHeight={900}
                                pauseOnPress={false}
                                showDuration={false}
                                autoplay={true}
                                disableSeek={true}
                                hideControlsOnStart={true}/>

this code not working in iOS

**Comment by jessica-lemarchand** [comment]
same issue...

**Comment by shail-spreadd** [comment]
any solution ?

**Comment by tanzeel152** [comment]
same issue
